### ISSUE TITLE
ldap module error

### ISSUE THREAD

**Issue by architmodi** [architmodi/rhos-bot#2]
While running the bot for the first time in a virtualenv:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 765, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/rhos-bot/modules/main.py", line 81, in search_thread
    ldap_connection = myldap.connect()
  File "/root/rhos-bot/modules/ldap_query.py", line 14, in connect
    ldap_connection = ldap.initialize('ldap://ldap.corp.redhat.com')
AttributeError: 'module' object has no attribute 'initialize'

**Comment by architmodi** [comment]
This error occurs when you run this in virtualenv. For now there is no specific resolution just that do not run it in virtualenv.
